// Code generated by "json2go --package main --typename Example --varname Examples --root /data --structure map,map,map --output example.go example1.json example2.json"; DO NOT EDIT.

package main

type Example struct{
	GroupB struct{
		Charley struct{
			Age int `json:"age"`
			Id string `json:"id"`
			Name string `json:"name"`
		} `json:"charley"`
	} `json:"groupB"`
}


var Examples = map[string]map[string]map[string]Example{
	"personGroups": {
		"groupB": {
			"charley": {
				Age: 53,
				Id: "7c6f9333-79e9-4d6b-84fd-5da3d28e3e19",
				Name: "charley",
			},
		}
		,
	}
	,
}
